#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 08, 2021 09:55:54 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pyHigher

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    pyHigher.set_Tk_var()
    top = Toplevel1(root)
    pyHigher.init(root, top)
    # root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel(root)
    pyHigher.set_Tk_var()
    top = Toplevel1(w)
    pyHigher.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):

        self.top = tk.Tk()

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        # self.VO2 = 0
        # self.VCO2 = 0
        # self.VE = 0
        # self.HR = 0


        self.top.geometry("398x222+532+258")
        self.top.minsize(120, 1)
        self.top.maxsize(1924, 1061)
        self.top.resizable(0,  0)
        self.top.title("pyHigher - 102Lab OCR Software")
        self.top.configure(background="#3f3f3f")
        self.top.configure(highlightbackground="#d9d9d9")
        self.top.configure(highlightcolor="black")

        self.StartButton = tk.Button(top)
        self.StartButton.place(x=300, y=50, height=58, width=79)
        self.StartButton.configure(activebackground="#ececec")
        self.StartButton.configure(activeforeground="#000000")
        self.StartButton.configure(background="#acacac")
        self.StartButton.configure(disabledforeground="#a3a3a3")
        self.StartButton.configure(font="-family {Microsoft YaHei UI} -size 12 -weight bold")
        self.StartButton.configure(foreground="#ffffff")
        self.StartButton.configure(highlightbackground="#d9d9d9")
        self.StartButton.configure(highlightcolor="#000000")
        self.StartButton.configure(pady="0")
        self.StartButton.configure(text='''Start''')

        self.StopButtom = tk.Button(top)
        self.StopButtom.place(x=302, y=140, height=58, width=79)
        self.StopButtom.configure(activebackground="#ececec")
        self.StopButtom.configure(activeforeground="#000000")
        self.StopButtom.configure(background="#acacac")
        self.StopButtom.configure(disabledforeground="#a3a3a3")
        self.StopButtom.configure(font="-family {Microsoft YaHei UI} -size 12 -weight bold")
        self.StopButtom.configure(foreground="#ffffff")
        self.StopButtom.configure(highlightbackground="#d9d9d9")
        self.StopButtom.configure(highlightcolor="black")
        self.StopButtom.configure(pady="0")
        self.StopButtom.configure(text='''Stop''')

        self.Text = tk.Text(top)
        self.Text.place(x=20, y=50, height=152, width=259)
        self.Text.configure(background="#7f7f7f")
        self.Text.configure(font="-family {Microsoft YaHei UI} -size 10 -weight bold")
        self.Text.configure(foreground="#ffffff")
        self.Text.configure(highlightbackground="#ffffff")
        self.Text.configure(highlightcolor="black")
        self.Text.configure(insertbackground="black")
        self.Text.configure(relief="flat")
        self.Text.configure(selectbackground="blue")
        self.Text.configure(selectforeground="#ffffff")
        self.Text.configure(wrap="word")

        self.VO2Check = tk.Checkbutton(top)
        self.VO2Check.place(x=20, y=10, height=27, width=63)
        self.VO2Check.configure(activebackground="#ececec")
        self.VO2Check.configure(activeforeground="#000000")
        self.VO2Check.configure(background="#3f3f3f")
        self.VO2Check.configure(disabledforeground="#a3a3a3")
        self.VO2Check.configure(font="-family {Microsoft YaHei UI} -size 9 -weight bold")
        self.VO2Check.configure(foreground="#ffffff")
        self.VO2Check.configure(highlightbackground="#acacac")
        self.VO2Check.configure(highlightcolor="#000000")
        self.VO2Check.configure(justify='left')
        self.VO2Check.configure(offrelief="flat")
        self.VO2Check.configure(selectcolor="#acacac")
        self.VO2Check.configure(text='''VO2''')
        # self.VO2Check.configure(variable=self.VO2)

        self.VCO2Check = tk.Checkbutton(top)
        self.VCO2Check.place(x=80, y=10, height=27, width=63)
        self.VCO2Check.configure(activebackground="#ececec")
        self.VCO2Check.configure(activeforeground="#000000")
        self.VCO2Check.configure(background="#3f3f3f")
        self.VCO2Check.configure(disabledforeground="#a3a3a3")
        self.VCO2Check.configure(font="-family {Microsoft YaHei UI} -size 9 -weight bold")
        self.VCO2Check.configure(foreground="#ffffff")
        self.VCO2Check.configure(highlightbackground="#acacac")
        self.VCO2Check.configure(highlightcolor="black")
        self.VCO2Check.configure(justify='left')
        self.VCO2Check.configure(selectcolor="#acacac")
        self.VCO2Check.configure(text='''VCO2''')
        # self.VCO2Check.configure(variable=self.VCO2)

        self.VECheck = tk.Checkbutton(top)
        self.VECheck.place(x=140, y=10, height=27, width=63)
        self.VECheck.configure(activebackground="#ececec")
        self.VECheck.configure(activeforeground="#000000")
        self.VECheck.configure(background="#3f3f3f")
        self.VECheck.configure(disabledforeground="#a3a3a3")
        self.VECheck.configure(font="-family {Microsoft YaHei UI} -size 9 -weight bold")
        self.VECheck.configure(foreground="#ffffff")
        self.VECheck.configure(highlightbackground="#acacac")
        self.VECheck.configure(highlightcolor="black")
        self.VECheck.configure(justify='left')
        self.VECheck.configure(selectcolor="#acacac")
        self.VECheck.configure(text='''VE''')
        # self.VECheck.configure(variable=pyHigher.VE)

        self.HRCheck = tk.Checkbutton(top)
        self.HRCheck.place(x=200, y=10, height=27, width=63)
        self.HRCheck.configure(activebackground="#ececec")
        self.HRCheck.configure(activeforeground="#000000")
        self.HRCheck.configure(background="#3f3f3f")
        self.HRCheck.configure(disabledforeground="#a3a3a3")
        self.HRCheck.configure(font="-family {Microsoft YaHei UI} -size 9 -weight bold")
        self.HRCheck.configure(foreground="#ffffff")
        self.HRCheck.configure(highlightbackground="#acacac")
        self.HRCheck.configure(highlightcolor="black")
        self.HRCheck.configure(justify='left')
        self.HRCheck.configure(selectcolor="#acacac")
        self.HRCheck.configure(text='''HR''')
        # self.HRCheck.configure(variable=pyHigher.HR)

        
if __name__ == '__main__':
    vp_start_gui()





